// Единый реестр DOM-элементов интерфейса (все id — из статического index.html).
// Экспортируем «живые» let-привязки: initDom() заполняет их один раз на старте,
// а модули-импортёры всегда видят актуальное значение (live bindings ES-модулей).
// Правило: рефы читаются только внутри функций (после initDom), никогда — на
// верхнем уровне модуля; присваиваются ТОЛЬКО здесь.

export let messagesEl: HTMLElement;
export let feedEl: HTMLElement;
export let emptyStateEl: HTMLElement;
export let inputEl: HTMLTextAreaElement;
export let sendBtn: HTMLButtonElement;
export let stopBtn: HTMLButtonElement;
export let modelSelectEl: HTMLSelectElement;
export let statusEl: HTMLElement;
export let engineEl: HTMLElement;
export let refreshBtn: HTMLButtonElement;
export let hwBarEl: HTMLElement;
export let hwWordEl: HTMLElement;
export let hwSpecsEl: HTMLElement;
export let hwModelEl: HTMLElement;
export let hwModelNameEl: HTMLElement;
export let convListEl: HTMLElement;
export let newChatBtn: HTMLButtonElement;
export let thinkToggleEl: HTMLButtonElement;
// Онлайн-режим (агентный): тумблер в композере, индикатор в шапке, поля и журнал в настройках.
export let onlineToggleEl: HTMLButtonElement;
export let onlineBadgeEl: HTMLElement;
export let onlineStateTextEl: HTMLElement;
export let onlineMasterToggleEl: HTMLButtonElement;
export let wsProviderEl: HTMLInputElement;
export let wsUrlEl: HTMLInputElement;
export let wsKeyEl: HTMLInputElement;
export let outboundLogEl: HTMLElement;
export let outboundRefreshBtn: HTMLButtonElement;
export let outboundClearBtn: HTMLButtonElement;
export let onlineStatusEl: HTMLElement;
export let themeBtn: HTMLButtonElement;
export let themeIconEl: HTMLElement;
export let settingsBtn: HTMLButtonElement;
export let settingsView: HTMLElement;
export let settingsBackBtn: HTMLButtonElement;
export let composerWrapEl: HTMLElement;
export let appEl: HTMLElement;
export let sidebarResizer: HTMLElement;
export let sidebarToggleBtn: HTMLButtonElement;
export let convSearchEl: HTMLInputElement;
export let checkBtn: HTMLButtonElement;
export let clearBtn: HTMLButtonElement;
export let attachBtn: HTMLButtonElement;
export let docChipEl: HTMLElement;
export let docChipBadgeEl: HTMLElement;
export let docChipNameEl: HTMLElement;
export let docRemoveBtn: HTMLButtonElement;
export let imageBtn: HTMLButtonElement;
export let imgChipEl: HTMLElement;
export let imgChipThumb: HTMLImageElement;
export let imgOcrBtn: HTMLButtonElement;
export let imgRemoveBtn: HTMLButtonElement;
export let tabChatsBtn: HTMLButtonElement;
export let tabDocsBtn: HTMLButtonElement;
export let paneChatsEl: HTMLElement;
export let paneDocsEl: HTMLElement;
export let addDocBtn: HTMLButtonElement;
export let docListEl: HTMLElement;
export let docStatusEl: HTMLElement;
export let docStatusTextEl: HTMLElement;
export let installEmbedBtn: HTMLButtonElement;
export let installLocalBtn: HTMLButtonElement;
export let pullCancelBtn: HTMLButtonElement;
export let epModelsEl: HTMLElement;
export let epEngineEl: HTMLElement;
export let epSetModelsBtn: HTMLButtonElement;
export let epSetEngineBtn: HTMLButtonElement;
export let epResetBtn: HTMLButtonElement;
export let settingsStatusEl: HTMLElement;
export let modelListEl: HTMLElement;
export let checkUpdatesBtn: HTMLButtonElement;
export let installFromDiskBtn: HTMLButtonElement;
export let modelsStatusEl: HTMLElement;
export let modelProgressEl: HTMLElement;
export let modelProgressFill: HTMLElement;
export let modelProgressLabel: HTMLElement;
export let modelPullCancelBtn: HTMLButtonElement;
export let diagRunBtn: HTMLButtonElement;
export let diagListEl: HTMLElement;
export let appUpdateCheckBtn: HTMLButtonElement;
export let appUpdateDiskBtn: HTMLButtonElement;
export let appUpdateInfoEl: HTMLElement;
export let appUpdateProgressEl: HTMLElement;
export let appUpdateProgressFill: HTMLElement;
export let appUpdateProgressLabel: HTMLElement;
export let appUpdateStatusEl: HTMLElement;
export let appVersionEl: HTMLElement;
export let indexProgressEl: HTMLElement;
export let indexProgressFill: HTMLElement;
export let indexProgressLabel: HTMLElement;
// Проекты: боковая панель, экран проекта, знания и чаты проекта.
export let projectListEl: HTMLElement;
export let newProjectBtn: HTMLButtonElement;
export let projectView: HTMLElement;
export let projectBackBtn: HTMLButtonElement;
export let projectNameInput: HTMLInputElement;
export let projectDeleteBtn: HTMLButtonElement;
export let projectInstructionsEl: HTMLTextAreaElement;
export let projectStatusEl: HTMLElement;
export let projectAddDocBtn: HTMLButtonElement;
export let projectDocListEl: HTMLElement;
export let projectChatListEl: HTMLElement;
export let projectIndexProgressEl: HTMLElement;
export let projectIndexProgressFill: HTMLElement;
export let projectIndexProgressLabel: HTMLElement;
export let projectNewChatBtn: HTMLButtonElement;
export let chatProjectChip: HTMLButtonElement;
export let chatProjectChipName: HTMLElement;

// Заполнить все рефы (вызывается ПЕРВЫМ в DOMContentLoaded, до любой инициализации).
export function initDom(): void {
  messagesEl = document.querySelector("#messages")!;
  feedEl = document.querySelector("#feed")!;
  emptyStateEl = document.querySelector("#empty-state")!;
  inputEl = document.querySelector("#chat-input")!;
  sendBtn = document.querySelector("#send-btn")!;
  stopBtn = document.querySelector("#stop-btn")!;
  modelSelectEl = document.querySelector("#model-select")!;
  statusEl = document.querySelector("#status")!;
  engineEl = document.querySelector("#engine")!;
  refreshBtn = document.querySelector("#refresh-btn")!;
  hwBarEl = document.querySelector("#hw-bar")!;
  hwWordEl = document.querySelector("#hw-word")!;
  hwSpecsEl = document.querySelector("#hw-specs")!;
  hwModelEl = document.querySelector("#hw-model")!;
  hwModelNameEl = document.querySelector("#hw-model-name")!;
  convListEl = document.querySelector("#conv-list")!;
  newChatBtn = document.querySelector("#new-chat-btn")!;
  thinkToggleEl = document.querySelector("#think-toggle")!;
  onlineToggleEl = document.querySelector("#online-toggle")!;
  onlineBadgeEl = document.querySelector("#online-badge")!;
  onlineStateTextEl = document.querySelector("#online-state-text")!;
  onlineMasterToggleEl = document.querySelector("#online-master-toggle")!;
  wsProviderEl = document.querySelector("#ws-provider")!;
  wsUrlEl = document.querySelector("#ws-url")!;
  wsKeyEl = document.querySelector("#ws-key")!;
  outboundLogEl = document.querySelector("#outbound-log")!;
  outboundRefreshBtn = document.querySelector("#outbound-refresh")!;
  outboundClearBtn = document.querySelector("#outbound-clear")!;
  onlineStatusEl = document.querySelector("#online-status")!;
  themeBtn = document.querySelector("#theme-btn")!;
  themeIconEl = document.querySelector("#theme-icon")!;
  settingsBtn = document.querySelector("#settings-btn")!;
  settingsView = document.querySelector("#settings-view")!;
  settingsBackBtn = document.querySelector("#settings-back")!;
  composerWrapEl = document.querySelector("#chat-form")!;
  appEl = document.querySelector(".app")!;
  sidebarResizer = document.querySelector("#sidebar-resizer")!;
  sidebarToggleBtn = document.querySelector("#sidebar-toggle")!;
  convSearchEl = document.querySelector("#conv-search")!;
  checkBtn = document.querySelector("#check-btn")!;
  clearBtn = document.querySelector("#clear-btn")!;
  attachBtn = document.querySelector("#attach-btn")!;
  docChipEl = document.querySelector("#doc-chip")!;
  docChipBadgeEl = document.querySelector("#doc-chip-badge")!;
  docChipNameEl = document.querySelector("#doc-chip-name")!;
  docRemoveBtn = document.querySelector("#doc-remove")!;
  imageBtn = document.querySelector("#image-btn")!;
  imgChipEl = document.querySelector("#img-chip")!;
  imgChipThumb = document.querySelector("#img-chip-thumb")!;
  imgOcrBtn = document.querySelector("#img-ocr")!;
  imgRemoveBtn = document.querySelector("#img-remove")!;
  tabChatsBtn = document.querySelector("#tab-chats-btn")!;
  tabDocsBtn = document.querySelector("#tab-docs-btn")!;
  paneChatsEl = document.querySelector("#pane-chats")!;
  paneDocsEl = document.querySelector("#pane-docs")!;
  addDocBtn = document.querySelector("#add-doc-btn")!;
  docListEl = document.querySelector("#doc-list")!;
  docStatusEl = document.querySelector("#doc-status")!;
  docStatusTextEl = document.querySelector("#doc-status-text")!;
  installEmbedBtn = document.querySelector("#install-embed-btn")!;
  installLocalBtn = document.querySelector("#install-local-btn")!;
  pullCancelBtn = document.querySelector("#pull-cancel-btn")!;
  epModelsEl = document.querySelector("#ep-models")!;
  epEngineEl = document.querySelector("#ep-engine")!;
  epSetModelsBtn = document.querySelector("#ep-set-models")!;
  epSetEngineBtn = document.querySelector("#ep-set-engine")!;
  epResetBtn = document.querySelector("#ep-reset")!;
  settingsStatusEl = document.querySelector("#settings-status")!;
  modelListEl = document.querySelector("#model-list")!;
  checkUpdatesBtn = document.querySelector("#check-updates-btn")!;
  installFromDiskBtn = document.querySelector("#install-from-disk-btn")!;
  modelsStatusEl = document.querySelector("#models-status")!;
  modelProgressEl = document.querySelector("#model-progress")!;
  modelProgressFill = document.querySelector("#model-progress-fill")!;
  modelProgressLabel = document.querySelector("#model-progress-label")!;
  modelPullCancelBtn = document.querySelector("#model-pull-cancel")!;
  diagRunBtn = document.querySelector("#diag-run-btn")!;
  diagListEl = document.querySelector("#diag-list")!;
  appUpdateCheckBtn = document.querySelector("#app-update-check")!;
  appUpdateDiskBtn = document.querySelector("#app-update-disk")!;
  appUpdateInfoEl = document.querySelector("#app-update-info")!;
  appUpdateProgressEl = document.querySelector("#app-update-progress")!;
  appUpdateProgressFill = document.querySelector("#app-update-progress-fill")!;
  appUpdateProgressLabel = document.querySelector("#app-update-progress-label")!;
  appUpdateStatusEl = document.querySelector("#app-update-status")!;
  appVersionEl = document.querySelector("#app-version")!;
  indexProgressEl = document.querySelector("#index-progress")!;
  indexProgressFill = document.querySelector("#index-progress-fill")!;
  indexProgressLabel = document.querySelector("#index-progress-label")!;
  projectListEl = document.querySelector("#project-list")!;
  newProjectBtn = document.querySelector("#new-project-btn")!;
  projectView = document.querySelector("#project-view")!;
  projectBackBtn = document.querySelector("#project-back")!;
  projectNameInput = document.querySelector("#project-name-input")!;
  projectDeleteBtn = document.querySelector("#project-delete")!;
  projectInstructionsEl = document.querySelector("#project-instructions")!;
  projectStatusEl = document.querySelector("#project-status")!;
  projectAddDocBtn = document.querySelector("#project-add-doc")!;
  projectDocListEl = document.querySelector("#project-doc-list")!;
  projectChatListEl = document.querySelector("#project-chat-list")!;
  projectIndexProgressEl = document.querySelector("#project-index-progress")!;
  projectIndexProgressFill = document.querySelector("#project-index-progress-fill")!;
  projectIndexProgressLabel = document.querySelector("#project-index-progress-label")!;
  projectNewChatBtn = document.querySelector("#project-new-chat")!;
  chatProjectChip = document.querySelector("#chat-project-chip")!;
  chatProjectChipName = document.querySelector("#chat-project-chip-name")!;
}
